name: 'Mod Validation'

on:
  push:
    branches: ['main', 'development']
  pull_request:
    branches: ['main', 'development']

jobs:
  validate-scripts:
    name: 'Validate with Tiger'
    runs-on: self-hosted

    steps:
      - name: 'Checkout Mod Code'
        uses: actions/checkout@v4

      - name: 'Run Tiger Validation'
        shell: powershell
        run: |
          # --- Step 1: Get Variables ---
          $tigerExecutable = "${{ vars.TIGER_EXECUTABLE_PATH }}"
          $vanillaGamePath = "${{ vars.VANILLA_GAME_PATH }}"
          $modPath = "${{ vars.MOD_PATH }}"
          
          # --- Step 2: Verify Variables ---
          echo "Tiger Executable Path: $tigerExecutable"
          echo "Vanilla Game Path: $vanillaGamePath"
          echo "Mod Path: $modPath"
          
          if (-not (Test-Path $tigerExecutable)) {
            echo "ERROR: Tiger executable not found at '$tigerExecutable'"
            exit 1
          }
          if (-not (Test-Path $vanillaGamePath)) {
            echo "ERROR: Vanilla game path not found at '$vanillaGamePath'"
            exit 1
          }
          
          if (-not (Test-Path $modPath)) {
            echo "ERROR: Mod path not found at '$modPath'"
            exit 1
          }
          
          # --- Step 3: Run the Executable ---
          echo "--- Running Tiger ---"
          
          # We execute the .exe directly.
          # The '&' is the PowerShell "call operator", used to run commands with paths/arguments in variables.
          # We pass the arguments it expects, which are likely similar to the source code version.
          & $tigerExecutable $modPath --game "$vanillaGamePath" | Tee-Object -Variable tigerOutput

          echo "--- Analyzing Tiger Results ---"

          # Convert the output (which is an array of lines) into a single string for easier searching.
          $tigerOutputString = $tigerOutput | Out-String

          # Use a regular expression to find the "error: [number]" part of the summary line.
          $match = $tigerOutputString | Select-String -Pattern "error: (\d+)"

          # Check if we found the summary line and if there are errors
          if ($match -and ([int]$match.Matches[0].Groups[1].Value -gt 0)) {
            $errorCount = $match.Matches[0].Groups[1].Value
            echo "::error::Tiger reported $errorCount error(s). Failing the workflow."
            exit 1
          } else {
            echo "Tiger validation passed with no reportable errors."
          }