name: 'Mod Validation'

on:
  push:
    branches: ['main', 'development']
  pull_request:
    branches: ['main', 'development']

jobs:
  validate-scripts:
    name: 'Validate with Tiger'
    runs-on: self-hosted

    steps:
      - name: 'Debug Runner Environment'
        run: |
            echo "--- Who am I? ---"
            whoami
            
            echo "--- What is my PATH? ---"
            # This prints the PATH variable, which is the most critical piece of information.
            echo $env:PATH
            
            echo "--- Where is dotnet.exe located according to my PATH? ---"
            # This command searches the PATH for dotnet.exe.
            # If this fails, the PATH is definitely wrong.
            where.exe dotnet
            
            echo "--- What does dotnet --info say? ---"
            # This is the final test. We run the same command that works for you locally.
            dotnet --info
          shell: pwsh # Use PowerShell for consistent commands on Windows

      - name: 'Setup .NET SDK'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: 'Checkout Mod Code'
        uses: actions/checkout@v4

      - name: 'Debug: Show dotnet info before setup'
        run: dotnet --info

      # The build step can also use a variable if the checkout path is not predictable.
      - name: 'Clone and Build Tiger'
        run: |
          git clone https://github.com/ck3-tiger/tiger.git ${{ vars.TIGER_CHECKOUT_PATH }}
          dotnet build ${{ vars.TIGER_PROJECT_PATH }} --configuration Release

      - name: 'Run Tiger Validation'
        run: |
          echo "Starting validation against vanilla path: ${{ vars.VANILLA_GAME_PATH }}"
          
          # Use the variables from GitHub Settings instead of a hardcoded env block.
          # The ${{ vars.VARIABLE_NAME }} syntax is replaced by GitHub at runtime.
          dotnet run --project "${{ vars.TIGER_PROJECT_PATH }}" --configuration Release -- --vanilla-path "${{ vars.VANILLA_GAME_PATH }}" --path .