name: 'Mod Validation'

on:
  push:
    branches: ['main', 'development']
  pull_request:
    branches: ['main', 'development']

jobs:
  validate-scripts:
    name: 'Validate with Tiger'
    runs-on: self-hosted

    steps:
      - name: 'Checkout Mod Code'
        uses: actions/checkout@v4

      - name: 'Run Tiger Validation'
        shell: powershell
        run: |
          # --- Step 1: Get Variables ---
          $tigerExecutable = "${{ vars.TIGER_EXECUTABLE_PATH }}"
          $vanillaGamePath = "${{ vars.VANILLA_GAME_PATH }}"
          
          # --- Step 2: Verify Variables ---
          echo "Tiger Executable Path: $tigerExecutable"
          echo "Vanilla Game Path: $vanillaGamePath"
          
          if (-not (Test-Path $tigerExecutable)) {
            echo "ERROR: Tiger executable not found at '$tigerExecutable'"
            exit 1
          }
          if (-not (Test-Path $vanillaGamePath)) {
            echo "ERROR: Vanilla game path not found at '$vanillaGamePath'"
            exit 1
          }
          
          # --- Step 3: Run the Executable ---
          echo "--- Running Tiger ---"
          
          # We execute the .exe directly.
          # The '&' is the PowerShell "call operator", used to run commands with paths/arguments in variables.
          # We pass the arguments it expects, which are likely similar to the source code version.
          & $tigerExecutable --vanilla-path "$vanillaGamePath" --path "."