name: 'Mod Validation'

on:
  push:
    branches: ['main', 'development']
  pull_request:
    branches: ['main', 'development']

jobs:
  validate-scripts:
    name: 'Validate with Tiger'
    runs-on: self-hosted

    steps:
      - name: 'Checkout Mod Code'
        uses: actions/checkout@v4

      - name: 'Manually Add .NET to PATH'
        run: echo "C:\Program Files\dotnet" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: powershell

      - name: 'Run Tiger Validation'
        shell: powershell
        run: |
          # Ensure you have set these variables in your repository's Settings > Actions > Variables
          $tigerProjectPath = "${{ vars.TIGER_PROJECT_PATH }}"
          $vanillaGamePath = "${{ vars.VANILLA_GAME_PATH }}"

          echo "Starting validation against vanilla path: $vanillaGamePath"
          
          # Let's add a quick verification command here for confidence.
          echo "--- Verifying dotnet command ---"
          dotnet --version

          echo "--- Running Tiger ---"
          dotnet run --project $tigerProjectPath --configuration Release -- --vanilla-path "$vanillaGamePath" --path .