name: 'Mod Validation'

on:
  push:
    branches: ['main', 'development']
  pull_request:
    branches: ['main', 'development']

jobs:
  validate-scripts:
    name: 'Validate with Tiger'
    runs-on: self-hosted

    steps:
      - name: 'Checkout Mod Code'
        uses: actions/checkout@v4

      - name: 'Manually Add .NET to PATH'
        run: echo "C:\Program Files\dotnet" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: powershell

      - name: 'Run Tiger Validation'
        shell: powershell
        run: |
          # --- Step 1: Get Variables ---
          $tigerProjectPath = "${{ vars.TIGER_PROJECT_PATH }}"
          $vanillaGamePath = "${{ vars.VANILLA_GAME_PATH }}"

          # --- Step 2: Verify Variables (Good Debugging Practice) ---
          echo "Tiger Project Path: $tigerProjectPath"
          echo "Vanilla Game Path: $vanillaGamePath"

          # Check if the paths actually exist on the runner.
          if (-not (Test-Path $tigerProjectPath)) {
            echo "ERROR: Tiger project path not found at '$tigerProjectPath'"
            exit 1
          }
          if (-not (Test-Path $vanillaGamePath)) {
            echo "ERROR: Vanilla game path not found at '$vanillaGamePath'"
            exit 1
          }

          # --- Step 3: Build the Command and Run ---
          echo "--- Verifying dotnet command ---"
          dotnet --version

          echo "--- Running Tiger ---"
          # This is the corrected command.
          # We ensure that 'Release' is correctly passed as the value for '--configuration'.
          dotnet run --project $tigerProjectPath --configuration "Release" -- --vanilla-path "$vanillaGamePath" --path "."